#!/bin/sh
launchctl unload $(ls /System/Library/LaunchDaemons/ | grep -v logd | grep -v fud | grep -v ReportCrash | while read a; do printf /System/Library/LaunchDaemons/$a\ ; done)
launchctl unload /System/Library/NanoLaunchDaemons
sleep 1

launchctl load /Library/LaunchDaemons
launchctl load /System/Library/LaunchDaemons
launchctl load /System/Library/NanoLaunchDaemons
sleep 1

launchctl unload /Library/LaunchDaemons/com.openssh.sshd.plist
/usr/libexec/sshd-keygen-wrapper

exit 0
